let expenses = JSON.parse(localStorage.getItem('finora_expenses') || '[]');
let debts = JSON.parse(localStorage.getItem('finora_debts') || '[]');
let budget = Number(localStorage.getItem('finora_budget') || 0);
let reserve = Number(localStorage.getItem('finora_reserve') || 0);
let editingDebt = null;
let payingDebt = null;
const money = n => `S/ ${Number(n || 0).toLocaleString('es-PE', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const escapeHTML = value => String(value).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));

function save() { localStorage.setItem('finora_expenses', JSON.stringify(expenses)); localStorage.setItem('finora_debts', JSON.stringify(debts)); localStorage.setItem('finora_budget', budget); localStorage.setItem('finora_reserve', reserve); render(); }
function toast(message) { const el = document.getElementById('toast'); el.textContent = message; el.classList.add('show'); setTimeout(() => el.classList.remove('show'), 2600); }
function saveBudget() { budget = Number(document.getElementById('budget').value || 0); reserve = Number(document.getElementById('reserve').value || 0); save(); toast('Presupuesto actualizado'); }
function addExpense() { const d = desc.value.trim(), a = Number(amount.value), c = category.value; if (!d || !a) return toast('Completa la descripción y el monto'); expenses.unshift({ id: Date.now(), d, a, c, date: new Date().toISOString() }); desc.value = ''; amount.value = ''; save(); toast('Gasto registrado'); }
function deleteExpense(id) { expenses = expenses.filter(e => e.id !== id); save(); }
function addDebt() { const n = debtName.value.trim(), a = Number(debtAmount.value), f = debtDate.value; if (!n || !a) return toast('Completa el nombre y el monto de la deuda'); if (editingDebt !== null) { const d = debts[editingDebt]; d.n = n; d.total = Math.max(a, d.total - d.balance); d.balance = Math.min(d.balance, d.total); d.end = f; toast('Deuda actualizada'); } else { debts.unshift({ id: Date.now(), n, total: a, balance: a, end: f, payments: [] }); toast('Deuda agregada'); } cancelEdit(false); save(); }
function pay(i) { payingDebt = i; const d = debts[i]; document.getElementById('paymentTitle').textContent = `Abono a ${d.n}`; document.getElementById('paymentBalance').textContent = `Saldo pendiente: ${money(d.balance)}`; const input = document.getElementById('paymentAmount'); input.value = ''; input.max = d.balance; document.getElementById('paymentModal').classList.add('open'); document.getElementById('paymentModal').setAttribute('aria-hidden', 'false'); setTimeout(() => input.focus(), 100); }
function closePaymentModal() { payingDebt = null; const modal = document.getElementById('paymentModal'); modal.classList.remove('open'); modal.setAttribute('aria-hidden', 'true'); }
function submitPayment() { if (payingDebt === null) return; const d = debts[payingDebt]; const p = Number(document.getElementById('paymentAmount').value); if (!p || p <= 0) return toast('Ingresa un monto válido'); const paid = Math.min(p, d.balance); d.balance -= paid; d.payments.unshift({ id: Date.now(), date: new Date().toISOString(), amount: paid }); closePaymentModal(); save(); toast(d.balance === 0 ? '¡Deuda liquidada!' : 'Pago registrado'); }
function editDebt(i) { const d = debts[i]; editingDebt = i; debtName.value = d.n; debtAmount.value = d.total; debtDate.value = d.end || ''; debtSubmit.textContent = 'Guardar cambios'; cancelEditBtn().classList.remove('hidden'); document.getElementById('debtForm').scrollIntoView({ behavior: 'smooth', block: 'center' }); }
function cancelEdit(clear = true) { editingDebt = null; debtSubmit.textContent = 'Agregar deuda'; cancelEditBtn().classList.add('hidden'); if (clear) { debtName.value = ''; debtAmount.value = ''; debtDate.value = ''; } }
function resetDebtForm() { cancelEdit(false); debtName.value = ''; debtAmount.value = ''; debtDate.value = ''; debtName.focus(); }
function cancelEditBtn() { return document.getElementById('cancelEdit'); }
function deleteDebt(i) { if (!confirm(`¿Eliminar la deuda “${debts[i].n}”?`)) return; debts.splice(i, 1); save(); toast('Deuda eliminada'); }
function dueLabel(date) { if (!date) return 'Sin fecha de vencimiento'; const days = Math.ceil((new Date(date + 'T00:00:00') - new Date(new Date().toDateString())) / 86400000); if (days < 0) return `Venció hace ${Math.abs(days)} días`; if (days === 0) return 'Vence hoy'; if (days === 1) return 'Vence mañana'; return `En ${days} días`; }
function render() {
  const spent = expenses.reduce((s, e) => s + e.a, 0), debtTotal = debts.reduce((s, d) => s + d.balance, 0), available = budget - spent;
  budgetText.textContent = money(budget); spentText.textContent = money(spent); availableText.textContent = money(available); debtText.textContent = money(debtTotal); reserveText.textContent = `Reserva mínima: ${money(reserve)}`; spentDetail.textContent = `${expenses.length} movimiento${expenses.length === 1 ? '' : 's'}`; debtDetail.textContent = `${debts.filter(d => d.balance > 0).length} deudas activas`;
  const pct = budget ? Math.min(spent / budget * 100, 100) : 0; bar.style.width = pct + '%'; progressLabel.textContent = `${pct.toFixed(0)}% usado`; availableDetail.textContent = available < reserve ? '⚠ Por debajo de tu reserva' : 'Dentro de tu objetivo';
  smartMessage.textContent = !budget ? 'Empieza definiendo tu presupuesto mensual.' : available < 0 ? `Has excedido tu presupuesto por ${money(-available)}.` : pct >= 80 ? `Atención: ya usaste el ${pct.toFixed(0)}% de tu presupuesto.` : `Vas bien: te quedan ${money(available)} para este mes.`;
  document.getElementById('expenses').innerHTML = expenses.length ? expenses.slice(0, 6).map(e => `<div class="expense-row"><span class="category-dot ${e.c.toLowerCase()}"></span><div><strong>${escapeHTML(e.d)}</strong><small>${escapeHTML(e.c)} · ${new Date(e.date).toLocaleDateString('es-PE')}</small></div><b>− ${money(e.a)}</b><button aria-label="Eliminar gasto" class="icon-btn" onclick="deleteExpense(${e.id})">×</button></div>`).join('') : '<p class="empty">Aún no registras gastos.</p>';
  const groups = {}; expenses.forEach(e => groups[e.c] = (groups[e.c] || 0) + e.a); const highest = Math.max(...Object.values(groups), 1); categoryChart.innerHTML = Object.keys(groups).length ? Object.entries(groups).sort((a,b) => b[1]-a[1]).map(([c, v]) => `<div class="chart-row"><span>${escapeHTML(c)}</span><div class="chart-track"><i style="width:${v/highest*100}%"></i></div><b>${money(v)}</b></div>`).join('') : '<p class="empty">Los gastos por categoría aparecerán aquí.</p>';
  document.getElementById('debts').innerHTML = debts.length ? debts.map((d, i) => { const pr = d.total ? ((d.total-d.balance)/d.total*100) : 0; return `<article class="debt-card ${d.balance === 0 ? 'settled' : ''}"><div class="debt-card-top"><div><span class="debt-type">${d.balance === 0 ? 'LIQUIDADA' : 'DEUDA ACTIVA'}</span><h3>${escapeHTML(d.n)}</h3></div><div class="debt-actions"><button onclick="editDebt(${i})">Editar</button><button class="danger" onclick="deleteDebt(${i})">Eliminar</button></div></div><div class="debt-amount"><strong>${money(d.balance)}</strong><span>de ${money(d.total)}</span></div><div class="thin-progress"><i style="width:${pr}%"></i></div><div class="debt-footer"><span>${d.end ? dueLabel(d.end) + ' · ' + new Date(d.end + 'T00:00:00').toLocaleDateString('es-PE') : 'Sin vencimiento'}</span><button class="pay-btn" onclick="pay(${i})" ${d.balance === 0 ? 'disabled' : ''}>+ Registrar pago</button></div></article>`; }).join('') : '<div class="empty debt-empty">No tienes deudas registradas. Añade la primera arriba.</div>';
  const calendarDebts = debts.filter(d => d.balance > 0 && d.end).sort((a,b) => a.end.localeCompare(b.end)); calendar.innerHTML = calendarDebts.length ? calendarDebts.map(d => `<div class="due-item"><span class="date-box"><b>${new Date(d.end + 'T00:00:00').getDate()}</b><small>${new Date(d.end + 'T00:00:00').toLocaleDateString('es-PE',{month:'short'}).replace('.','')}</small></span><div><strong>${escapeHTML(d.n)}</strong><small>${dueLabel(d.end)} · ${money(d.balance)}</small></div></div>`).join('') : '<p class="empty">No hay vencimientos próximos.</p>';
  const payments = debts.flatMap(d => d.payments.map(p => ({...p, debt: d.n}))).sort((a,b) => new Date(b.date)-new Date(a.date)); paymentHistory.innerHTML = payments.length ? payments.map(p => `<div class="history-row"><span class="paid-icon">✓</span><div><strong>Pago a ${escapeHTML(p.debt)}</strong><small>${new Date(p.date).toLocaleDateString('es-PE',{dateStyle:'long'})}</small></div><b>${money(p.amount)}</b></div>`).join('') : '<p class="empty">Los abonos que registres aparecerán aquí.</p>';
}
function downloadExcel() { const rows = [['Tipo','Descripción','Categoría','Monto','Fecha','Saldo pendiente'], ...expenses.map(e => ['Gasto',e.d,e.c,e.a,new Date(e.date).toLocaleDateString('es-PE'),'']), ...debts.map(d => ['Deuda',d.n,'',d.total,d.end || '',d.balance]), ...debts.flatMap(d => d.payments.map(p => ['Pago',d.n,'',p.amount,new Date(p.date).toLocaleDateString('es-PE'),d.balance]))]; const csv = '\uFEFF' + rows.map(row => row.map(x => `"${String(x).replace(/"/g,'""')}"`).join(';')).join('\n'); const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([csv], {type:'text/csv;charset=utf-8;'})); a.download = `finora-${new Date().toISOString().slice(0,10)}.csv`; a.click(); URL.revokeObjectURL(a.href); toast('Archivo listo para abrir en Excel'); }
document.getElementById('currentMonth').textContent = new Date().toLocaleDateString('es-PE',{month:'long', year:'numeric'});
document.getElementById('paymentModal').addEventListener('click', event => { if (event.target.id === 'paymentModal') closePaymentModal(); });
document.getElementById('paymentAmount').addEventListener('keydown', event => { if (event.key === 'Enter') submitPayment(); if (event.key === 'Escape') closePaymentModal(); });
document.getElementById('budget').value = budget || ''; document.getElementById('reserve').value = reserve || ''; render();
