let expenses = JSON.parse(localStorage.getItem('finora_expenses') || '[]');
let debts = JSON.parse(localStorage.getItem('finora_debts') || '[]');
let budget = Number(localStorage.getItem('finora_budget') || 0), reserve = Number(localStorage.getItem('finora_reserve') || 0);
let editingDebt = null, payingDebt = null, currentUser = null, isRegistering = false;
const money = n => `S/ ${Number(n || 0).toLocaleString('es-PE', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const escapeHTML = v => String(v).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const dataRef = () => financeDb.collection('users').doc(currentUser.uid).collection('private').doc('dashboard');

function toast(message) { const el = document.getElementById('toast'); el.textContent = message; el.classList.add('show'); setTimeout(() => el.classList.remove('show'), 2600); }
async function save() { if (!currentUser) return; localStorage.setItem('finora_expenses', JSON.stringify(expenses)); localStorage.setItem('finora_debts', JSON.stringify(debts)); localStorage.setItem('finora_budget', budget); localStorage.setItem('finora_reserve', reserve); render(); try { await dataRef().set({ expenses, debts, budget, reserve, updatedAt: firebase.firestore.FieldValue.serverTimestamp() }); } catch (error) { toast('No se pudo guardar en la nube'); console.error(error); } }
async function loadCloudData() { const snapshot = await dataRef().get(); if (snapshot.exists) { const d = snapshot.data(); expenses = Array.isArray(d.expenses) ? d.expenses : []; debts = Array.isArray(d.debts) ? d.debts : []; budget = Number(d.budget || 0); reserve = Number(d.reserve || 0); } else { await save(); } document.getElementById('budget').value = budget || ''; document.getElementById('reserve').value = reserve || ''; render(); }
function saveBudget() { budget = Number(document.getElementById('budget').value || 0); reserve = Number(document.getElementById('reserve').value || 0); save(); toast('Presupuesto actualizado'); }
function addExpense() { const d = desc.value.trim(), a = Number(amount.value), c = category.value; if (!d || !a) return toast('Completa la descripción y el monto'); expenses.unshift({ id: Date.now(), d, a, c, date: new Date().toISOString() }); desc.value = ''; amount.value = ''; save(); toast('Gasto registrado'); }
function deleteExpense(id) { expenses = expenses.filter(e => e.id !== id); save(); }
function addDebt() { const n = debtName.value.trim(), a = Number(debtAmount.value), f = debtDate.value; if (!n || !a) return toast('Completa el nombre y el monto de la deuda'); if (editingDebt !== null) { const d = debts[editingDebt]; d.n = n; d.total = Math.max(a, d.total - d.balance); d.balance = Math.min(d.balance, d.total); d.end = f; toast('Deuda actualizada'); } else { debts.unshift({ id: Date.now(), n, total: a, balance: a, end: f, payments: [] }); toast('Deuda agregada'); } cancelEdit(false); save(); }
function pay(i) { payingDebt = i; const d = debts[i], input = document.getElementById('paymentAmount'); document.getElementById('paymentTitle').textContent = `Abono a ${d.n}`; document.getElementById('paymentBalance').textContent = `Saldo pendiente: ${money(d.balance)}`; input.value = ''; input.max = d.balance; document.getElementById('paymentModal').classList.add('open'); setTimeout(() => input.focus(), 100); }
function closePaymentModal() { payingDebt = null; document.getElementById('paymentModal').classList.remove('open'); }
function submitPayment() { if (payingDebt === null) return; const d = debts[payingDebt], p = Number(document.getElementById('paymentAmount').value); if (!p || p <= 0) return toast('Ingresa un monto válido'); const paid = Math.min(p, d.balance); d.balance -= paid; d.payments.unshift({ id: Date.now(), date: new Date().toISOString(), amount: paid }); closePaymentModal(); save(); toast(d.balance === 0 ? '¡Deuda liquidada!' : 'Pago registrado'); }
function editDebt(i) { const d = debts[i]; editingDebt = i; debtName.value = d.n; debtAmount.value = d.total; debtDate.value = d.end || ''; debtSubmit.textContent = 'Guardar cambios'; document.getElementById('cancelEdit').classList.remove('hidden'); document.getElementById('debtForm').scrollIntoView({ behavior: 'smooth', block: 'center' }); }
function cancelEdit(clear = true) { editingDebt = null; debtSubmit.textContent = 'Agregar deuda'; document.getElementById('cancelEdit').classList.add('hidden'); if (clear) { debtName.value = ''; debtAmount.value = ''; debtDate.value = ''; } }
function resetDebtForm() { cancelEdit(false); debtName.value = ''; debtAmount.value = ''; debtDate.value = ''; debtName.focus(); }
function deleteDebt(i) { if (!confirm(`¿Eliminar la deuda “${debts[i].n}”?`)) return; debts.splice(i, 1); save(); toast('Deuda eliminada'); }
function dueLabel(date) { if (!date) return 'Sin fecha de vencimiento'; const days = Math.ceil((new Date(date + 'T00:00:00') - new Date(new Date().toDateString())) / 86400000); return days < 0 ? `Venció hace ${Math.abs(days)} días` : days === 0 ? 'Vence hoy' : days === 1 ? 'Vence mañana' : `En ${days} días`; }
function render() { const spent = expenses.reduce((s,e) => s + e.a, 0), debtTotal = debts.reduce((s,d) => s + d.balance, 0), available = budget - spent, pct = budget ? Math.min(spent / budget * 100,100) : 0;
  budgetText.textContent=money(budget); spentText.textContent=money(spent); availableText.textContent=money(available); debtText.textContent=money(debtTotal); reserveText.textContent=`Reserva mínima: ${money(reserve)}`; spentDetail.textContent=`${expenses.length} movimiento${expenses.length===1?'':'s'}`; debtDetail.textContent=`${debts.filter(d=>d.balance>0).length} deudas activas`; bar.style.width=pct+'%'; progressLabel.textContent=`${pct.toFixed(0)}% usado`; availableDetail.textContent=available<reserve?'⚠ Por debajo de tu reserva':'Dentro de tu objetivo'; smartMessage.textContent=!budget?'Empieza definiendo tu presupuesto mensual.':available<0?`Has excedido tu presupuesto por ${money(-available)}.`:pct>=80?`Atención: ya usaste el ${pct.toFixed(0)}% de tu presupuesto.`:`Vas bien: te quedan ${money(available)} para este mes.`;
  document.getElementById('expenses').innerHTML=expenses.length?expenses.slice(0,6).map(e=>`<div class="expense-row"><span class="category-dot ${e.c.toLowerCase()}"></span><div><strong>${escapeHTML(e.d)}</strong><small>${escapeHTML(e.c)} · ${new Date(e.date).toLocaleDateString('es-PE')}</small></div><b>− ${money(e.a)}</b><button aria-label="Eliminar gasto" class="icon-btn" onclick="deleteExpense(${e.id})">×</button></div>`).join(''):'<p class="empty">Aún no registras gastos.</p>';
  const groups={};expenses.forEach(e=>groups[e.c]=(groups[e.c]||0)+e.a);const highest=Math.max(...Object.values(groups),1);categoryChart.innerHTML=Object.keys(groups).length?Object.entries(groups).sort((a,b)=>b[1]-a[1]).map(([c,v])=>`<div class="chart-row"><span>${escapeHTML(c)}</span><div class="chart-track"><i style="width:${v/highest*100}%"></i></div><b>${money(v)}</b></div>`).join(''):'<p class="empty">Los gastos por categoría aparecerán aquí.</p>';
  document.getElementById('debts').innerHTML=debts.length?debts.map((d,i)=>{const pr=d.total?((d.total-d.balance)/d.total*100):0;return `<article class="debt-card ${d.balance===0?'settled':''}"><div class="debt-card-top"><div><span class="debt-type">${d.balance===0?'LIQUIDADA':'DEUDA ACTIVA'}</span><h3>${escapeHTML(d.n)}</h3></div><div class="debt-actions"><button onclick="editDebt(${i})">Editar</button><button class="danger" onclick="deleteDebt(${i})">Eliminar</button></div></div><div class="debt-amount"><strong>${money(d.balance)}</strong><span>de ${money(d.total)}</span></div><div class="thin-progress"><i style="width:${pr}%"></i></div><div class="debt-footer"><span>${d.end?dueLabel(d.end)+' · '+new Date(d.end+'T00:00:00').toLocaleDateString('es-PE'):'Sin vencimiento'}</span><button class="pay-btn" onclick="pay(${i})" ${d.balance===0?'disabled':''}>+ Registrar pago</button></div></article>`;}).join(''):'<div class="empty debt-empty">No tienes deudas registradas. Añade la primera arriba.</div>';
  const dated=debts.filter(d=>d.balance>0&&d.end).sort((a,b)=>a.end.localeCompare(b.end));calendar.innerHTML=dated.length?dated.map(d=>`<div class="due-item"><span class="date-box"><b>${new Date(d.end+'T00:00:00').getDate()}</b><small>${new Date(d.end+'T00:00:00').toLocaleDateString('es-PE',{month:'short'}).replace('.','')}</small></span><div><strong>${escapeHTML(d.n)}</strong><small>${dueLabel(d.end)} · ${money(d.balance)}</small></div></div>`).join(''):'<p class="empty">No hay vencimientos próximos.</p>';
  const payments=debts.flatMap(d=>d.payments.map(p=>({...p,debt:d.n}))).sort((a,b)=>new Date(b.date)-new Date(a.date));paymentHistory.innerHTML=payments.length?payments.map(p=>`<div class="history-row"><span class="paid-icon">✓</span><div><strong>Pago a ${escapeHTML(p.debt)}</strong><small>${new Date(p.date).toLocaleDateString('es-PE',{dateStyle:'long'})}</small></div><b>${money(p.amount)}</b></div>`).join(''):'<p class="empty">Los abonos que registres aparecerán aquí.</p>'; }
function downloadExcel(){const rows=[['Tipo','Descripción','Categoría','Monto','Fecha','Saldo pendiente'],...expenses.map(e=>['Gasto',e.d,e.c,e.a,new Date(e.date).toLocaleDateString('es-PE'),'']),...debts.map(d=>['Deuda',d.n,'',d.total,d.end||'',d.balance]),...debts.flatMap(d=>d.payments.map(p=>['Pago',d.n,'',p.amount,new Date(p.date).toLocaleDateString('es-PE'),d.balance]))],csv='\uFEFF'+rows.map(r=>r.map(x=>`"${String(x).replace(/"/g,'""')}"`).join(';')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8;'}));a.download=`finora-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href);toast('Archivo listo para abrir en Excel');}
function setAuthMode(register){isRegistering=register;authTitle.textContent=register?'Crea tu cuenta':'Ingresa a tu espacio';authText.textContent=register?'Tus datos se guardarán de forma segura en la nube.':'Accede para ver tus datos en todos tus dispositivos.';authSubmit.textContent=register?'Crear cuenta':'Ingresar';authToggle.textContent=register?'¿Ya tienes cuenta? Ingresar':'¿No tienes cuenta? Crear cuenta';authPassword.autocomplete=register?'new-password':'current-password';authError.textContent='';}
document.getElementById('authForm').addEventListener('submit',async e=>{e.preventDefault();const email=authEmail.value.trim(),password=authPassword.value;authError.textContent='';try{if(isRegistering)await financeAuth.createUserWithEmailAndPassword(email,password);else await financeAuth.signInWithEmailAndPassword(email,password);}catch(error){console.error('Firebase Authentication:',error.code,error.message);const messages={'auth/email-already-in-use':'Este correo ya tiene una cuenta. Pulsa “Ingresar”.','auth/invalid-email':'Ingresa un correo válido.','auth/weak-password':'La contraseña debe tener al menos 6 caracteres.','auth/invalid-credential':'Correo o contraseña incorrectos.','auth/unauthorized-domain':'Este sitio no está autorizado en Firebase. Revisa el dominio autorizado.','auth/operation-not-allowed':'El acceso por correo y contraseña no está habilitado en Firebase.','auth/network-request-failed':'No se pudo conectar con Firebase. Revisa tu conexión e inténtalo otra vez.','auth/api-key-not-valid':'La configuración de Firebase no es válida. Vuelve a subir firebase-init.js.'};authError.textContent=messages[error.code]||`Firebase indicó: ${error.code||'error desconocido'}.`;}});document.getElementById('authToggle').addEventListener('click',()=>setAuthMode(!isRegistering));
document.getElementById('currentMonth').textContent=new Date().toLocaleDateString('es-PE',{month:'long',year:'numeric'});document.getElementById('paymentModal').addEventListener('click',e=>{if(e.target.id==='paymentModal')closePaymentModal();});document.getElementById('paymentAmount').addEventListener('keydown',e=>{if(e.key==='Enter')submitPayment();if(e.key==='Escape')closePaymentModal();});
financeAuth.onAuthStateChanged(async user=>{currentUser=user;if(!user){document.getElementById('authScreen').classList.add('visible');return;}document.getElementById('authScreen').classList.remove('visible');try{await loadCloudData();}catch(error){console.error(error);toast('No se pudieron cargar los datos de la nube');}});
